- name: Create database 'ecomdb'
  become: true
  mysql_db:
    name: ecomdb
    state: present
- name: Create user 'ecomuser'
  become: true
  mysql_user:
    name: ecomuser
    password: 'ecompassword'
    priv: '*.*:ALL'
    state: present