---
- name: Configure database
  tasks:
    - name: Create database 'ecomdb'
      mysql_db:
        name: ecomdb
        state: present
    - name: Create user 'ecomuser'
      mysql_user:
        name: ecomuser
        password: 'ecompassword'
        priv: '*.*:ALL'
        state: present
