- name: Install mariadb-server
  become: true
  yum:
      name: mariadb-server
      state: present
- name: Start mariadb-server
  become: true
  service:
      name: mariadb
      state: started
      enabled: true