- name: Update EPEL
  become: true
  yum:
    name: epel-release
    state: latest
- name: Install prerequisites
  become: true
  yum:
    name:
      - firewalld
      - python-pip
- name: Upgrade pip
  become:  true
  pip:
    name:
      - pip<21.0
    extra_args: --upgrade
- name: Install PyMySQL
  become:  true
  pip:
    name:
      - pymysql
    state: present
- name: Start FirewallD
  become: true
  service:
    name: firewalld
    state: started
    enabled: true